export default {
  kind: "youtube#liveChatMessageListResponse",
  etag: "zNH2HD9Pp8fVjnI4AuHLHIxUn8w",
  pollingIntervalMillis: 4782,
  pageInfo: {
    totalResults: 67,
    resultsPerPage: 67,
  },
  nextPageToken: "GMXrgsiOxusCIJ2p-8qOxusC",
  items: [
    {
      kind: "youtube#liveChatMessage",
      etag: "mVrFjqk1pP-lEVd_CN8fWQjDBZY",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSmY5X3F5T3h1c0NGVU82Z2dvZDlKSUFpdxInQ05qSHRaLU94dXNDRlY0YXR3QWQ4ZlVLSncxNTk4ODk5OTE2MTc2",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCsizB36lcaH5XvHc9zdak5Q",
        publishedAt: "2020-08-31T18:51:57.667000Z",
        hasDisplayContent: true,
        displayMessage: "bye goodnight",
        textMessageDetails: {
          messageText: "bye goodnight",
        },
      },
      authorDetails: {
        channelId: "UCsizB36lcaH5XvHc9zdak5Q",
        channelUrl: "http://www.youtube.com/channel/UCsizB36lcaH5XvHc9zdak5Q",
        displayName: "Webdunia English",
        profileImageUrl: "https://yt3.ggpht.com/-71T2Yq5HuQ0/AAAAAAAAAAI/AAAAAAAAAAA/1D3AjYedKtg/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "TBRmA9GzZ8DgBMbK3NOkT3O2PNU",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDT25KcWEyT3h1c0NGWXV3Z2dvZFFYOEdYQRInQ0k2dDY2aU94dXNDRlVwWmp3b2RwUEVFekExNTk4ODk5OTE3NzYx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCEH1deKt160BrTbFTdwm6Fw",
        publishedAt: "2020-08-31T18:51:58.365000Z",
        hasDisplayContent: true,
        displayMessage: "congratulation bro",
        textMessageDetails: {
          messageText: "congratulation bro",
        },
      },
      authorDetails: {
        channelId: "UCEH1deKt160BrTbFTdwm6Fw",
        channelUrl: "http://www.youtube.com/channel/UCEH1deKt160BrTbFTdwm6Fw",
        displayName: "Rajesh Sahu",
        profileImageUrl: "https://yt3.ggpht.com/-jgLrJElqbPg/AAAAAAAAAAI/AAAAAAAAAAA/UbxF3CUpKTA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "Y1JjLP8PEPCJywd-WWnsIGbX2No",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDT3V5cDYyT3h1c0NGWnlDd2dFZEk5QUNCZxInQ05lNW81U094dXNDRlJmeGFBb2QzczBIT0ExNTk4ODk5OTgxMjEw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCip5-YVAB6envPJfukGcJHg",
        publishedAt: "2020-08-31T18:51:58.330000Z",
        hasDisplayContent: true,
        displayMessage: ":dothefive::elbowbump:",
        textMessageDetails: {
          messageText: ":dothefive::elbowbump:",
        },
      },
      authorDetails: {
        channelId: "UCip5-YVAB6envPJfukGcJHg",
        channelUrl: "http://www.youtube.com/channel/UCip5-YVAB6envPJfukGcJHg",
        displayName: "Suman Rokde",
        profileImageUrl: "https://yt3.ggpht.com/-eBWI4yh7aN8/AAAAAAAAAAI/AAAAAAAAAAA/UaxoF_c1ObE/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "B0vebhBq8ZejP55qtD9ScBMsYac",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSm1hejYyT3h1c0NGY2V6Z2dvZHNMWU1VZxInQ1BDMDY2bU94dXNDRmVFRzFRb2RpV1FQWXcxNTk4ODk5OTE4MzE4",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCXXcCauLX8UIHCkwO1-I46Q",
        publishedAt: "2020-08-31T18:51:58.982000Z",
        hasDisplayContent: true,
        displayMessage: "6m op",
        textMessageDetails: {
          messageText: "6m op",
        },
      },
      authorDetails: {
        channelId: "UCXXcCauLX8UIHCkwO1-I46Q",
        channelUrl: "http://www.youtube.com/channel/UCXXcCauLX8UIHCkwO1-I46Q",
        displayName: "TOD Rx BLadE",
        profileImageUrl: "https://yt3.ggpht.com/-YF9S-ni8w3c/AAAAAAAAAAI/AAAAAAAAAAA/PmP57UF1MsA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "ncrHNLdcdP4k_HZVv-nuFQQaVKc",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI5ChpDTHF0aks2T3h1c0NGUXE4Z2dvZE5nVUNxdxIbQ0o3TTlmNk54dXNDRmNoMEtnb2R3czRGZ3cw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCx1UessMKwexBNbWe9kJIxw",
        publishedAt: "2020-08-31T18:51:59.984000Z",
        hasDisplayContent: true,
        displayMessage: "wah wah mortal wah",
        textMessageDetails: {
          messageText: "wah wah mortal wah",
        },
      },
      authorDetails: {
        channelId: "UCx1UessMKwexBNbWe9kJIxw",
        channelUrl: "http://www.youtube.com/channel/UCx1UessMKwexBNbWe9kJIxw",
        displayName: "Upasana Verma",
        profileImageUrl: "https://yt3.ggpht.com/-RIJKoAaJliU/AAAAAAAAAAI/AAAAAAAAAAA/rMoutXZwKL4/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "wKzz2wgogARbrot676kuAsbSQoE",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDT213cGE2T3h1c0NGYUZEN1FvZHF0RUh4dxInQ0lQN3U1cU94dXNDRlE4UjFRb2RvazBENkExNTk4ODk5OTE5NTgx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCenL33f4QNrcQKYL10mIW0g",
        publishedAt: "2020-08-31T18:52:00.394000Z",
        hasDisplayContent: true,
        displayMessage: "Soul op bolte haters ki maa cho******************dte",
        textMessageDetails: {
          messageText: "Soul op bolte haters ki maa cho******************dte",
        },
      },
      authorDetails: {
        channelId: "UCenL33f4QNrcQKYL10mIW0g",
        channelUrl: "http://www.youtube.com/channel/UCenL33f4QNrcQKYL10mIW0g",
        displayName: "Dhruvin Parikh",
        profileImageUrl: "https://yt3.ggpht.com/-68lDEXc16h0/AAAAAAAAAAI/AAAAAAAAAAA/Rner857f5uI/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "YCubjezGctgrHFTwmKsMJ2o2064",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSmFFb2E2T3h1c0NGU0lqZ3dvZHM2MEFXURInQ05tQWpxR094dXNDRlVHQmNBb2RYbUVCaGcxNTk4ODk5OTIzMTA2",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCRQXY_C5Nef5L_GOPzD2Ygg",
        publishedAt: "2020-08-31T18:52:00.323000Z",
        hasDisplayContent: true,
        displayMessage: "Bhai aaj Mera b day hai",
        textMessageDetails: {
          messageText: "Bhai aaj Mera b day hai",
        },
      },
      authorDetails: {
        channelId: "UCRQXY_C5Nef5L_GOPzD2Ygg",
        channelUrl: "http://www.youtube.com/channel/UCRQXY_C5Nef5L_GOPzD2Ygg",
        displayName: "SREEDHAR PALIVELA",
        profileImageUrl: "https://yt3.ggpht.com/-_UTMTpyBsWo/AAAAAAAAAAI/AAAAAAAAAAA/T7fnzMrGYlY/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "9AXk92m9AYF4aZhTqUCxTkJG46A",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTnJwcXE2T3h1c0NGVlM2Z2dvZDZUY0FrQRInQ0pfWG9xV094dXNDRmRILU9BWWRPaE1JaHcxNTk4ODk5OTE5Mzk4",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC57jtYwV-WDowfgHF--3VmQ",
        publishedAt: "2020-08-31T18:52:00.483000Z",
        hasDisplayContent: true,
        displayMessage: "shukar hai becharey ke 6 M hogye",
        textMessageDetails: {
          messageText: "shukar hai becharey ke 6 M hogye",
        },
      },
      authorDetails: {
        channelId: "UC57jtYwV-WDowfgHF--3VmQ",
        channelUrl: "http://www.youtube.com/channel/UC57jtYwV-WDowfgHF--3VmQ",
        displayName: "Self Made Rapper",
        profileImageUrl: "https://yt3.ggpht.com/-W9S2DhnFcQY/AAAAAAAAAAI/AAAAAAAAAAA/jfXB1Wl4zCE/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "zWDUGPStinGaf1MergiR6qR4QTY",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTENIaHEtT3h1c0NGYWVBd2dFZEI2MEgwdxInQ0xUbjZabUx4dXNDRllNVnR3QWRMLUFFR3cxNTk4ODk5OTIwOTgz",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC8cxDTBEK_zYe0tjm-RShag",
        publishedAt: "2020-08-31T18:52:01.978000Z",
        hasDisplayContent: true,
        displayMessage: "comitted op",
        textMessageDetails: {
          messageText: "comitted op",
        },
      },
      authorDetails: {
        channelId: "UC8cxDTBEK_zYe0tjm-RShag",
        channelUrl: "http://www.youtube.com/channel/UC8cxDTBEK_zYe0tjm-RShag",
        displayName: "لبیک یآ حسین",
        profileImageUrl: "https://yt3.ggpht.com/-LaGrhsvIDnc/AAAAAAAAAAI/AAAAAAAAAAA/tJieldLrKYU/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "Vl83Vlq285zX_Ed7XRYaSLbNyMU",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDUGZSMjYtT3h1c0NGWEhnZ2dvZEFTUUhhZxInQ1BucjlwR094dXNDRlNUaWN3RWRzcFVDQncxNTk4ODk5OTIxOTkz",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCF6WbVeeajTu7TYfq9lN53A",
        publishedAt: "2020-08-31T18:52:03.380000Z",
        hasDisplayContent: true,
        displayMessage: "hii",
        textMessageDetails: {
          messageText: "hii",
        },
      },
      authorDetails: {
        channelId: "UCF6WbVeeajTu7TYfq9lN53A",
        channelUrl: "http://www.youtube.com/channel/UCF6WbVeeajTu7TYfq9lN53A",
        displayName: "Rajkumar Sarvesh",
        profileImageUrl: "https://yt3.ggpht.com/-6r_h3J871HA/AAAAAAAAAAI/AAAAAAAAAAA/aVccqXOdRns/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "b6aBxWp4yW4wJ00dZRv1gtxihno",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDUExZOHJDT3h1c0NGWlBHZ2dvZHo5a1BLQRInQ0pHMDU1LUx4dXNDRmNNSTFRb2RQX3dNMGcxNTk4ODk5OTI0NjE3",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCvv3Bd3NOEJV4qO0KW12omA",
        publishedAt: "2020-08-31T18:52:05.855000Z",
        hasDisplayContent: true,
        displayMessage: "bhai aap ke 1k theh jab meine subscribe kiya tha",
        textMessageDetails: {
          messageText: "bhai aap ke 1k theh jab meine subscribe kiya tha",
        },
      },
      authorDetails: {
        channelId: "UCvv3Bd3NOEJV4qO0KW12omA",
        channelUrl: "http://www.youtube.com/channel/UCvv3Bd3NOEJV4qO0KW12omA",
        displayName: "TECHNICAL GAMING",
        profileImageUrl: "https://yt3.ggpht.com/-zAS2MSl-ZXs/AAAAAAAAAAI/AAAAAAAAAAA/NvaqoCfpDqY/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "F7AuiscZU6DuNEHR6HDuilp2I7U",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTS1uaExLT3h1c0NGWWFiZ2dvZHdSSUM0URInQ0tYcnJhMk94dXNDRmJMbWN3RWRONWNMM1ExNTk4ODk5OTI3NjEw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCo6oyzH3bMZVA9E4uVmpw8w",
        publishedAt: "2020-08-31T18:52:08.241000Z",
        hasDisplayContent: true,
        displayMessage: "congrats on 6m",
        textMessageDetails: {
          messageText: "congrats on 6m",
        },
      },
      authorDetails: {
        channelId: "UCo6oyzH3bMZVA9E4uVmpw8w",
        channelUrl: "http://www.youtube.com/channel/UCo6oyzH3bMZVA9E4uVmpw8w",
        displayName: "Aditya Priya",
        profileImageUrl: "https://yt3.ggpht.com/-G6355xBjEOk/AAAAAAAAAAI/AAAAAAAAAAA/jn2oD15simY/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "AN8HjzgDNxEcMKUpwujGGMXvFXk",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTkRFbTdLT3h1c0NGU1JIN1FvZE1PNEZqdxInQ01uRW02dU94dXNDRlhZVHR3QWRWWUVPQVExNTk4ODk5OTI3ODk5",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCHAG_9BKWvo-cnuKpjXNDcA",
        publishedAt: "2020-08-31T18:52:08.621000Z",
        hasDisplayContent: true,
        displayMessage: "6m congratulations",
        textMessageDetails: {
          messageText: "6m congratulations",
        },
      },
      authorDetails: {
        channelId: "UCHAG_9BKWvo-cnuKpjXNDcA",
        channelUrl: "http://www.youtube.com/channel/UCHAG_9BKWvo-cnuKpjXNDcA",
        displayName: "Lazin Magar",
        profileImageUrl: "https://yt3.ggpht.com/-n2b3tNaz-A0/AAAAAAAAAAI/AAAAAAAAAAA/iEfrCx_H9os/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "XfBpFto6vASclgCxBvUhs3BhA-E",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI6ChpDTzNIdkxLT3h1c0NGUWpPZ2dvZGFGOEZxZxIcQ0lMWDY2dU94dXNDRlhzUjhRVWRpeG9QaFEtMA",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC-vAQZANVv7oGqPrPkR0C6g",
        publishedAt: "2020-08-31T18:52:09.162000Z",
        hasDisplayContent: true,
        displayMessage: "Congratulations",
        textMessageDetails: {
          messageText: "Congratulations",
        },
      },
      authorDetails: {
        channelId: "UC-vAQZANVv7oGqPrPkR0C6g",
        channelUrl: "http://www.youtube.com/channel/UC-vAQZANVv7oGqPrPkR0C6g",
        displayName: "Afnan Ijaz",
        profileImageUrl: "https://yt3.ggpht.com/-VN80iR53Tsw/AAAAAAAAAAI/AAAAAAAAAAA/HiSXjkriqhQ/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "slcphO9zi7aeP8wULK18Kfh73vE",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDS2FXdHJPT3h1c0NGUkpVN1FvZER5TU1YURInQ0luZzNLcU94dXNDRlVIbk9BWWROUzhHcGcxNTk4ODk5OTMwMDAy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCwQY2H8UTzsQGSt_uRXjP7g",
        publishedAt: "2020-08-31T18:52:11.155000Z",
        hasDisplayContent: true,
        displayMessage: "congratulations",
        textMessageDetails: {
          messageText: "congratulations",
        },
      },
      authorDetails: {
        channelId: "UCwQY2H8UTzsQGSt_uRXjP7g",
        channelUrl: "http://www.youtube.com/channel/UCwQY2H8UTzsQGSt_uRXjP7g",
        displayName: "Mahesh ACHARYA",
        profileImageUrl: "https://yt3.ggpht.com/-96GMFzQT--E/AAAAAAAAAAI/AAAAAAAAAAA/4W4qxkFHd6w/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "GLNY7yXzhW01irEi-jxsx-HOxEs",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI5ChpDSjZFeUxPT3h1c0NGWU5ON1FvZHBzc0QwURIbQ05XZTc3Nkh4dXNDRlNULU9BWWRNT2tQOVEw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCbulJSqPhQ_iYa51udTn1iA",
        publishedAt: "2020-08-31T18:52:11.447000Z",
        hasDisplayContent: true,
        displayMessage: "nightbot help",
        textMessageDetails: {
          messageText: "nightbot help",
        },
      },
      authorDetails: {
        channelId: "UCbulJSqPhQ_iYa51udTn1iA",
        channelUrl: "http://www.youtube.com/channel/UCbulJSqPhQ_iYa51udTn1iA",
        displayName: "vipul kewlani",
        profileImageUrl: "https://yt3.ggpht.com/-2nrXYgFohAQ/AAAAAAAAAAI/AAAAAAAAAAA/tKUOQDevO_w/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "SXD68Mf0g3Y6qSiqkMeZr9UPDZg",
      id: "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRIcChpDTWkzMTdPT3h1c0NGWjJGd2dFZHF4Y0d4Zw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        publishedAt: "2020-08-31T18:52:11.700000Z",
        hasDisplayContent: true,
        displayMessage: "No religious discussions. Humanity above all.",
        textMessageDetails: {
          messageText: "No religious discussions. Humanity above all.",
        },
      },
      authorDetails: {
        channelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        channelUrl: "http://www.youtube.com/channel/UCSvjQBDgYDB5TGVmCZObcwA",
        displayName: "Nightbot",
        profileImageUrl: "https://yt3.ggpht.com/-TGo4_AHc7Po/AAAAAAAAAAI/AAAAAAAAAAA/6X489lMTauA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: true,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: true,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "NYVMZLER9wZEJmbIUzzlsSLldxU",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDT3V6aGJTT3h1c0NGUkpVN1FvZF9ad01SZxInQ1B1bm43Nk54dXNDRlZnU3R3QWR2akFIdVExNTk4ODk5OTMxMTI5",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCO-vL3MR7o_8k_kzvKazg6Q",
        publishedAt: "2020-08-31T18:52:12.453000Z",
        hasDisplayContent: true,
        displayMessage: "nooooo",
        textMessageDetails: {
          messageText: "nooooo",
        },
      },
      authorDetails: {
        channelId: "UCO-vL3MR7o_8k_kzvKazg6Q",
        channelUrl: "http://www.youtube.com/channel/UCO-vL3MR7o_8k_kzvKazg6Q",
        displayName: "Tajinder Singh",
        profileImageUrl: "https://yt3.ggpht.com/-rGbfhVtYYFo/AAAAAAAAAAI/AAAAAAAAAAA/S2_tcK4XknE/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "hFgjDm4t7X12FqpC_QD4zGbTgUA",
      id: "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRIcChpDS3FDbGJTT3h1c0NGWWpPZ2dvZExoZ0ZTUQ",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        publishedAt: "2020-08-31T18:52:12.709000Z",
        hasDisplayContent: true,
        displayMessage: "Nightbot toh rega ka bhai h xD",
        textMessageDetails: {
          messageText: "Nightbot toh rega ka bhai h xD",
        },
      },
      authorDetails: {
        channelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        channelUrl: "http://www.youtube.com/channel/UCSvjQBDgYDB5TGVmCZObcwA",
        displayName: "Nightbot",
        profileImageUrl: "https://yt3.ggpht.com/-TGo4_AHc7Po/AAAAAAAAAAI/AAAAAAAAAAA/6X489lMTauA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: true,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: true,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "jBw4neJTHGJP3jYO2Fywa5FpGBI",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTVBnakxhT3h1c0NGWW0zRFFvZEVEOE9fQRInQ0xIdS03S094dXNDRlN6SmN3RWRWUklCQ3cxNTk4ODk5OTM3NTMw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCz_BqApVsvMHVK43nNgNPsQ",
        publishedAt: "2020-08-31T18:52:16.768000Z",
        hasDisplayContent: true,
        displayMessage: "6m congratulations",
        textMessageDetails: {
          messageText: "6m congratulations",
        },
      },
      authorDetails: {
        channelId: "UCz_BqApVsvMHVK43nNgNPsQ",
        channelUrl: "http://www.youtube.com/channel/UCz_BqApVsvMHVK43nNgNPsQ",
        displayName: "Vedant Gyanchandani",
        profileImageUrl: "https://yt3.ggpht.com/-g0kmEkm8eYo/AAAAAAAAAAI/AAAAAAAAAAA/vUcz3wx59Uk/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "DFYsNly-0D27jwn4vX8bQRSRgis",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDS2U0c3JhT3h1c0NGUk9rZ2dvZGV4Y0FIQRInQ0xqZXJheU94dXNDRlhuYU9BWWRtd3NBUFExNTk4ODk5OTM2Njg5",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCYrW_WBWq9TI_ibkMTGrTEg",
        publishedAt: "2020-08-31T18:52:17.385000Z",
        hasDisplayContent: true,
        displayMessage: "6 million subscribers:goodvibes:",
        textMessageDetails: {
          messageText: "6 million subscribers:goodvibes:",
        },
      },
      authorDetails: {
        channelId: "UCYrW_WBWq9TI_ibkMTGrTEg",
        channelUrl: "http://www.youtube.com/channel/UCYrW_WBWq9TI_ibkMTGrTEg",
        displayName: "Monika Mandekar",
        profileImageUrl: "https://yt3.ggpht.com/-cixwdAUdo-Q/AAAAAAAAAAI/AAAAAAAAAAA/JnQN9E6-MDc/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "WNGg9-wrwDEdU7hb1OF-ttULCsk",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTHpzcExlT3h1c0NGWldQZ2dvZHBCd0t2ZxInQ0tLT2phdU94dXNDRlFoTGp3b2RkMndFNWcxNTk4ODk5OTM4MzUx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCxsHdcVjk3KxLieYlToEorQ",
        publishedAt: "2020-08-31T18:52:19.259000Z",
        hasDisplayContent: true,
        displayMessage: "hi op",
        textMessageDetails: {
          messageText: "hi op",
        },
      },
      authorDetails: {
        channelId: "UCxsHdcVjk3KxLieYlToEorQ",
        channelUrl: "http://www.youtube.com/channel/UCxsHdcVjk3KxLieYlToEorQ",
        displayName: "THE FREQUENCY GAMING",
        profileImageUrl: "https://yt3.ggpht.com/-kGSfFyRx2iw/AAAAAAAAAAI/AAAAAAAAAAA/m2EIAfg-TQ4/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "h_0EnfwGR7Q63MOXBqZLqDoL2OY",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTjJRc3JpT3h1c0NGUlN3Z2dvZDZIWUhGdxInQ0pmVmo3U094dXNDRmEzbGN3RWRwcmtPZHcxNTk4ODk5OTQyMDI2",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCBHGMLn0sCb05LsoswxDvng",
        publishedAt: "2020-08-31T18:52:21.574000Z",
        hasDisplayContent: true,
        displayMessage: "6m Congratulations",
        textMessageDetails: {
          messageText: "6m Congratulations",
        },
      },
      authorDetails: {
        channelId: "UCBHGMLn0sCb05LsoswxDvng",
        channelUrl: "http://www.youtube.com/channel/UCBHGMLn0sCb05LsoswxDvng",
        displayName: "BeRLiN",
        profileImageUrl: "https://yt3.ggpht.com/-6B14hqc0NlM/AAAAAAAAAAI/AAAAAAAAAAA/4l9x028swIM/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "CRw4RmWjgly3tN9mjJfIpslc_rI",
      id: "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRIcChpDUFBEdXJpT3h1c0NGUmFKZ2dvZHR5d0hLQQ",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        publishedAt: "2020-08-31T18:52:21.712000Z",
        hasDisplayContent: true,
        displayMessage: "Hello @THE FREQUENCY GAMING welcome to the stream 😍",
        textMessageDetails: {
          messageText: "Hello @THE FREQUENCY GAMING welcome to the stream 😍",
        },
      },
      authorDetails: {
        channelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        channelUrl: "http://www.youtube.com/channel/UCSvjQBDgYDB5TGVmCZObcwA",
        displayName: "Nightbot",
        profileImageUrl: "https://yt3.ggpht.com/-TGo4_AHc7Po/AAAAAAAAAAI/AAAAAAAAAAA/6X489lMTauA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: true,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: true,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "ohGTUVHJCdy25PrquG24mwMEkcE",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSnZpMTdpT3h1c0NGWldwRFFvZGZUMEg2URInQ0tXWm5ZS094dXNDRlVQdmFBb2RVbzRHWmcxNTk4ODk5OTQxMTY3",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCG-i5da4IpSWPVgU9OkW4rA",
        publishedAt: "2020-08-31T18:52:22.191000Z",
        hasDisplayContent: true,
        displayMessage: "maa kasam bro. i am watching you from 20",
        textMessageDetails: {
          messageText: "maa kasam bro. i am watching you from 20",
        },
      },
      authorDetails: {
        channelId: "UCG-i5da4IpSWPVgU9OkW4rA",
        channelUrl: "http://www.youtube.com/channel/UCG-i5da4IpSWPVgU9OkW4rA",
        displayName: "Hupesh Naik",
        profileImageUrl: "https://yt3.ggpht.com/-xmpQ_Qq5Du0/AAAAAAAAAAI/AAAAAAAAAAA/rQUgF7wiOgE/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "vmkP92WTrYkCWVa0AwRqvMM4XuU",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTTZyMmJpT3h1c0NGUU5hN1FvZHRia0xYdxInQ01pTm83YU94dXNDRlh2LU9BWWRGamNOUWcxNTk4ODk5OTQxMDAw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCS6x6_QIEbzD2vNlzkQSeMA",
        publishedAt: "2020-08-31T18:52:22.217000Z",
        hasDisplayContent: true,
        displayMessage: "hellloooo",
        textMessageDetails: {
          messageText: "hellloooo",
        },
      },
      authorDetails: {
        channelId: "UCS6x6_QIEbzD2vNlzkQSeMA",
        channelUrl: "http://www.youtube.com/channel/UCS6x6_QIEbzD2vNlzkQSeMA",
        displayName: "Rishi Thevar",
        profileImageUrl: "https://yt3.ggpht.com/-L5iw_LC4i38/AAAAAAAAAAI/AAAAAAAAAAA/1s2n-mBPO8Y/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: true,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "s2YwDFV9wgdhCB_a-IjvLZ1Vk0Q",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSVhXLWJpT3h1c0NGYzJEd2dFZDl3MEdvURInQ0pfR3hMS094dXNDRlJMTmFBb2RGSXdQc2cxNTk4ODk5OTQxNTU3",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCuJCcwJujwYYbv78CtlqXyg",
        publishedAt: "2020-08-31T18:52:22.746000Z",
        hasDisplayContent: true,
        displayMessage: "6m ol",
        textMessageDetails: {
          messageText: "6m ol",
        },
      },
      authorDetails: {
        channelId: "UCuJCcwJujwYYbv78CtlqXyg",
        channelUrl: "http://www.youtube.com/channel/UCuJCcwJujwYYbv78CtlqXyg",
        displayName: "APOCALYPSE LIVE",
        profileImageUrl: "https://yt3.ggpht.com/-ChpjHSLDNfU/AAAAAAAAAAI/AAAAAAAAAAA/ZEW1acFOb00/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "L7NiLO6cm8UNOFF9FKrtREO4dqU",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTld4Z3JtT3h1c0NGUi1Ed2dFZDFQVU1RQRInQ011TjBaLU94dXNDRmM3ck9BWWRqUDhCSkExNTk4ODk5OTQxODA3",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCKpawBY8_y3V-HvAGP606cw",
        publishedAt: "2020-08-31T18:52:22.889000Z",
        hasDisplayContent: true,
        displayMessage: ",6 m op",
        textMessageDetails: {
          messageText: ",6 m op",
        },
      },
      authorDetails: {
        channelId: "UCKpawBY8_y3V-HvAGP606cw",
        channelUrl: "http://www.youtube.com/channel/UCKpawBY8_y3V-HvAGP606cw",
        displayName: "shinchan*X op",
        profileImageUrl: "https://yt3.ggpht.com/-8qU48Wgscn8/AAAAAAAAAAI/AAAAAAAAAAA/KGoN0yGwlak/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "P6Jd1_chqWftEqAFFPEuM8Cv5h0",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTi1xX0xpT3h1c0NGVWlxZ2dvZG9QME9qQRInQ051Z29ZU094dXNDRlZxQVl3WWRTQnNPa2cxNTk4ODk5OTQwNTM5",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCn8gQ5yotw_0vZBvpNvH-nw",
        publishedAt: "2020-08-31T18:52:22.790000Z",
        hasDisplayContent: true,
        displayMessage:
          "Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭",
        textMessageDetails: {
          messageText:
            "Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais Ronak Owais 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭",
        },
      },
      authorDetails: {
        channelId: "UCn8gQ5yotw_0vZBvpNvH-nw",
        channelUrl: "http://www.youtube.com/channel/UCn8gQ5yotw_0vZBvpNvH-nw",
        displayName: "Yash More",
        profileImageUrl: "https://yt3.ggpht.com/-CO-R7C3gA0g/AAAAAAAAAAI/AAAAAAAAAAA/pKBNnq2A_zM/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "b01FHZJAjyME4aaF-oaa0DFPNBg",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTVdabDdtT3h1c0NGWXVwRFFvZHpiZ1B5dxInQ042azlMT094dXNDRld6T2N3RWQtRWtMcGcxNTk4ODk5OTQyNzIy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCxCax4Ao_5K0c4bbhemyB7A",
        publishedAt: "2020-08-31T18:52:23.230000Z",
        hasDisplayContent: true,
        displayMessage: "Happy 6 Million bhai",
        textMessageDetails: {
          messageText: "Happy 6 Million bhai",
        },
      },
      authorDetails: {
        channelId: "UCxCax4Ao_5K0c4bbhemyB7A",
        channelUrl: "http://www.youtube.com/channel/UCxCax4Ao_5K0c4bbhemyB7A",
        displayName: "Jems Dave",
        profileImageUrl: "https://yt3.ggpht.com/-l2fwU97Fuvk/AAAAAAAAAAI/AAAAAAAAAAA/Ng3PNYWoLyg/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "Vh3Fbyt8_7o0rwlYu2T7lkQi0EQ",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDUENwemJtT3h1c0NGUVdEZ2dvZFJ4OEZDQRInQ016MXBhdU94dXNDRlFsemFBb2RPYm9IbUExNTk4ODk5OTQxOTIx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC3uJrPaL6tTIXIU8Z5AtmLA",
        publishedAt: "2020-08-31T18:52:24.117000Z",
        hasDisplayContent: true,
        displayMessage: "congratsss bro",
        textMessageDetails: {
          messageText: "congratsss bro",
        },
      },
      authorDetails: {
        channelId: "UC3uJrPaL6tTIXIU8Z5AtmLA",
        channelUrl: "http://www.youtube.com/channel/UC3uJrPaL6tTIXIU8Z5AtmLA",
        displayName: "F4DED ROCKY",
        profileImageUrl: "https://yt3.ggpht.com/-QwRxzIXWeV4/AAAAAAAAAAI/AAAAAAAAAAA/g1dQvy1NYLU/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "hpo9dkHR7tXGsgWhqr9nLVfAu3M",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI6ChpDSkdqMDdtT3h1c0NGWW0zRFFvZGhXUUJXdxIcQ01Qd3Y3S094dXNDRlNKUGZBb2RiY3dBNlEtMA",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCXRUcQt9tRLyMBVrJS0X0qQ",
        publishedAt: "2020-08-31T18:52:24.214000Z",
        hasDisplayContent: true,
        displayMessage: "Blaezi boot camp kab aayega",
        textMessageDetails: {
          messageText: "Blaezi boot camp kab aayega",
        },
      },
      authorDetails: {
        channelId: "UCXRUcQt9tRLyMBVrJS0X0qQ",
        channelUrl: "http://www.youtube.com/channel/UCXRUcQt9tRLyMBVrJS0X0qQ",
        displayName: "Siddharth Bishnoi",
        profileImageUrl: "https://yt3.ggpht.com/-FQuRrEuOobs/AAAAAAAAAAI/AAAAAAAAAAA/VJtVfM2fII8/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "hAFqcWDDm4_HhVcGREPxIaK3R2s",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTTZ5N2JtT3h1c0NGVkM4Z2dvZDJXOENMQRInQ01yUTZZT094dXNDRlIwS3R3QWRTdUFBYncxNTk4ODk5OTQ0MDE2",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCwVa1qW7eQcD4vuymTu_DjQ",
        publishedAt: "2020-08-31T18:52:24.642000Z",
        hasDisplayContent: true,
        displayMessage: "6M OP ❤️❤️❤️🔥",
        textMessageDetails: {
          messageText: "6M OP ❤️❤️❤️🔥",
        },
      },
      authorDetails: {
        channelId: "UCwVa1qW7eQcD4vuymTu_DjQ",
        channelUrl: "http://www.youtube.com/channel/UCwVa1qW7eQcD4vuymTu_DjQ",
        displayName: "Sanjana Sen",
        profileImageUrl: "https://yt3.ggpht.com/-fAH2OfWEXiM/AAAAAAAAAAI/AAAAAAAAAAA/xKdjP5P3YWM/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: true,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "ckZNWKC3l09WJ003k7yrXbY2VFY",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSlBiXzdtT3h1c0NGUU1uZ3dvZDNmQUs3QRInQ0pPbXlMU094dXNDRlhEbE9BWWRuZXNDancxNTk4ODk5OTQ1Nzgy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCm_K4OvnaUD8wBQstHnegNA",
        publishedAt: "2020-08-31T18:52:24.942000Z",
        hasDisplayContent: true,
        displayMessage: "hello bro",
        textMessageDetails: {
          messageText: "hello bro",
        },
      },
      authorDetails: {
        channelId: "UCm_K4OvnaUD8wBQstHnegNA",
        channelUrl: "http://www.youtube.com/channel/UCm_K4OvnaUD8wBQstHnegNA",
        displayName: "Veer Rughani",
        profileImageUrl: "https://yt3.ggpht.com/-5-MxXIDio88/AAAAAAAAAAI/AAAAAAAAAAA/uu1RTdh-D38/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "fd34Ew73BSLSuO46h3CkcoURAjs",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI6ChpDS2lUNkxtT3h1c0NGYmFSd2dFZDBYSUtnZxIcQ0x2c3hiS094dXNDRmJud09BWWRnZzRMSVEtMA",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC3tuVPPEBgYx1O0vqNxKS0Q",
        publishedAt: "2020-08-31T18:52:24.556000Z",
        hasDisplayContent: true,
        displayMessage: "6million",
        textMessageDetails: {
          messageText: "6million",
        },
      },
      authorDetails: {
        channelId: "UC3tuVPPEBgYx1O0vqNxKS0Q",
        channelUrl: "http://www.youtube.com/channel/UC3tuVPPEBgYx1O0vqNxKS0Q",
        displayName: "YYBR BOLT",
        profileImageUrl: "https://yt3.ggpht.com/-vX2zDTlcwS8/AAAAAAAAAAI/AAAAAAAAAAA/tZK7Ar11DOw/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "4kaotcv8JRyiJH0kZ14xNmDycMw",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTzIxbkxxT3h1c0NGWUhmZ2dvZEdJa0pQURInQ05uY3U3YU94dXNDRmRlRWNBb2QyeUVGYmcxNTk4ODk5OTQ1MDMy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCXfrFMPrpNbBTzpbCrO9jpQ",
        publishedAt: "2020-08-31T18:52:25.413000Z",
        hasDisplayContent: true,
        displayMessage: "6m",
        textMessageDetails: {
          messageText: "6m",
        },
      },
      authorDetails: {
        channelId: "UCXfrFMPrpNbBTzpbCrO9jpQ",
        channelUrl: "http://www.youtube.com/channel/UCXfrFMPrpNbBTzpbCrO9jpQ",
        displayName: "Manoj Bmkr",
        profileImageUrl: "https://yt3.ggpht.com/-ZBw1gKmmoGw/AAAAAAAAAAI/AAAAAAAAAAA/b60bOjCoUTA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "aoYQH7zO8YHY_U2fcxgM7Z47g-E",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSWpydHJxT3h1c0NGV1dFd2dFZHpIMEpwZxInQ09qbzY3Q094dXNDRmUzbTVnb2RaWUlHWEExNTk4ODk5OTQ1Mjc0",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCKR266kcsQ8pYgbrhZ_R_CA",
        publishedAt: "2020-08-31T18:52:25.846000Z",
        hasDisplayContent: true,
        displayMessage: "rega is soo cute 😝🤣🤦",
        textMessageDetails: {
          messageText: "rega is soo cute 😝🤣🤦",
        },
      },
      authorDetails: {
        channelId: "UCKR266kcsQ8pYgbrhZ_R_CA",
        channelUrl: "http://www.youtube.com/channel/UCKR266kcsQ8pYgbrhZ_R_CA",
        displayName: "Panda's Production",
        profileImageUrl: "https://yt3.ggpht.com/-d5lJOZ_FA5I/AAAAAAAAAAI/AAAAAAAAAAA/75BJ7-dd-Nc/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "ACTMPJXOlEGT52DDf76i39o8d3g",
      id: "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRIcChpDSnJEekxxT3h1c0NGUldEd2dFZGhqc0FYQQ",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        publishedAt: "2020-08-31T18:52:26.201000Z",
        hasDisplayContent: true,
        displayMessage: "Hello @Veer Rughani welcome to the stream 😍",
        textMessageDetails: {
          messageText: "Hello @Veer Rughani welcome to the stream 😍",
        },
      },
      authorDetails: {
        channelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        channelUrl: "http://www.youtube.com/channel/UCSvjQBDgYDB5TGVmCZObcwA",
        displayName: "Nightbot",
        profileImageUrl: "https://yt3.ggpht.com/-TGo4_AHc7Po/AAAAAAAAAAI/AAAAAAAAAAA/6X489lMTauA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: true,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: true,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "o4SJB1vIBVHlbQK9MdDwXjMUols",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTC1SNGJxT3h1c0NGUUxnZ2dvZExsVUNrQRInQ0szOHliYU94dXNDRlh6Z2N3RWRUX01Jd3cxNTk4ODk5OTQ1MjQx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCVq-vfouqWPvnj90CwlZiJw",
        publishedAt: "2020-08-31T18:52:26.539000Z",
        hasDisplayContent: true,
        displayMessage: "F",
        textMessageDetails: {
          messageText: "F",
        },
      },
      authorDetails: {
        channelId: "UCVq-vfouqWPvnj90CwlZiJw",
        channelUrl: "http://www.youtube.com/channel/UCVq-vfouqWPvnj90CwlZiJw",
        displayName: "KoMaL",
        profileImageUrl: "https://yt3.ggpht.com/-qYlv_h8Mvdg/AAAAAAAAAAI/AAAAAAAAAAA/BIaNz9S0XII/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "PQK3IzaWkrgcNb7mpPphDUAPnwk",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSi11cTd1T3h1c0NGYkxrZ2dvZExkb0NRURInQ0lmU2dibU94dXNDRmNPQ2NBb2R4dnNNancxNTk4ODk5OTQ3MzAy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC-suBxUwT1D79NF3P7W4g_g",
        publishedAt: "2020-08-31T18:52:27.755000Z",
        hasDisplayContent: true,
        displayMessage: "congo",
        textMessageDetails: {
          messageText: "congo",
        },
      },
      authorDetails: {
        channelId: "UC-suBxUwT1D79NF3P7W4g_g",
        channelUrl: "http://www.youtube.com/channel/UC-suBxUwT1D79NF3P7W4g_g",
        displayName: "GK GAMING",
        profileImageUrl: "https://yt3.ggpht.com/-00ZJHq2r9Ho/AAAAAAAAAAI/AAAAAAAAAAA/RYksI-JXw_4/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "yoU10xx8EP-yB7thUuUsWgIMwvM",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTWppNDd1T3h1c0NGVmFGd2dFZHItc0dTZxInQ1BYVTFiQ094dXNDRlJENE9BWWQxd3NBQ0ExNTk4ODk5OTQ3OTE3",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCGkKy_Y2bIt4EoVdJA41fnA",
        publishedAt: "2020-08-31T18:52:28.679000Z",
        hasDisplayContent: true,
        displayMessage: "6m op bolte",
        textMessageDetails: {
          messageText: "6m op bolte",
        },
      },
      authorDetails: {
        channelId: "UCGkKy_Y2bIt4EoVdJA41fnA",
        channelUrl: "http://www.youtube.com/channel/UCGkKy_Y2bIt4EoVdJA41fnA",
        displayName: "Dibyendu Dutta",
        profileImageUrl: "https://yt3.ggpht.com/-YX9S2g96aJ8/AAAAAAAAAAI/AAAAAAAAAAA/i7VbZRlYxnk/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "-RqhHpZ9Dn9BBuu8LdtvVy60cDE",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTGUtZ0x5T3h1c0NGUU5hN1FvZGRlUVA3ZxInQ0pfYTJiaU94dXNDRlVmOVVRb2RoaHNOTUExNTk4ODk5OTQ2NjU0",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCA12cesonQp36miuWXgG-lg",
        publishedAt: "2020-08-31T18:52:29.150000Z",
        hasDisplayContent: true,
        displayMessage: "bharwa",
        textMessageDetails: {
          messageText: "bharwa",
        },
      },
      authorDetails: {
        channelId: "UCA12cesonQp36miuWXgG-lg",
        channelUrl: "http://www.youtube.com/channel/UCA12cesonQp36miuWXgG-lg",
        displayName: "KILLER๛ HYDRA",
        profileImageUrl: "https://yt3.ggpht.com/-psf-l9ME3qo/AAAAAAAAAAI/AAAAAAAAAAA/DnhTrZb0zsQ/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "42_7alFFRcqb3VU7l7WdgJoG5iw",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI5ChpDSk9mbDd5T3h1c0NGUkY4Z3dvZFFvTUk1QRIbQ01tMi05Q014dXNDRlFqTGFBb2RySE1ETVE0",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCaZYiAK3wi_7IBw6knADUFw",
        publishedAt: "2020-08-31T18:52:29.522000Z",
        hasDisplayContent: true,
        displayMessage: "rega havas",
        textMessageDetails: {
          messageText: "rega havas",
        },
      },
      authorDetails: {
        channelId: "UCaZYiAK3wi_7IBw6knADUFw",
        channelUrl: "http://www.youtube.com/channel/UCaZYiAK3wi_7IBw6knADUFw",
        displayName: "VanSh A",
        profileImageUrl: "https://yt3.ggpht.com/-x71bxbeiJFQ/AAAAAAAAAAI/AAAAAAAAAAA/4jWrl6zJPFc/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "Psvz1V0dqYJdCvV1AyE9jGCxquQ",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTG5wcnJ5T3h1c0NGWVRLZ2dvZDh0RU9pQRInQ0xiZ3diU094dXNDRlFLRGNBb2RKOUFMZVExNTk4ODk5OTQ5MTMy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC0r-_oRUfaS-m8skiBPEC5Q",
        publishedAt: "2020-08-31T18:52:29.909000Z",
        hasDisplayContent: true,
        displayMessage: "support for students",
        textMessageDetails: {
          messageText: "support for students",
        },
      },
      authorDetails: {
        channelId: "UC0r-_oRUfaS-m8skiBPEC5Q",
        channelUrl: "http://www.youtube.com/channel/UC0r-_oRUfaS-m8skiBPEC5Q",
        displayName: "AFROJ ANSARI",
        profileImageUrl: "https://yt3.ggpht.com/-YG86nxF4DiY/AAAAAAAAAAI/AAAAAAAAAAA/tX9tZ_gmzwg/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "_vb29b1FM2vctV5wyEUJ1nXTFL4",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTUh1eXJ5T3h1c0NGUUczZ2dvZEtRc0ZJZxInQ01ubnBhbU94dXNDRldYdU9BWWQ3QTRJQ3cxNTk4ODk5OTQ4ODQ4",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCbSH7_-YcXwpt258x3eG5NA",
        publishedAt: "2020-08-31T18:52:30.368000Z",
        hasDisplayContent: true,
        displayMessage: "congrats for 6 million YouTube family 👪",
        textMessageDetails: {
          messageText: "congrats for 6 million YouTube family 👪",
        },
      },
      authorDetails: {
        channelId: "UCbSH7_-YcXwpt258x3eG5NA",
        channelUrl: "http://www.youtube.com/channel/UCbSH7_-YcXwpt258x3eG5NA",
        displayName: "Akash Gaming 7789",
        profileImageUrl: "https://yt3.ggpht.com/-JnVwdKBvCp0/AAAAAAAAAAI/AAAAAAAAAAA/mF8N2EU7W-4/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "WSuDa15zLfGrwPzhngTgJKm6QdE",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTkxTMHIyT3h1c0NGV05EN1FvZFREWUJqdxInQ01EeC03S094dXNDRlJkWGFBb2Rmd0FLakExNTk4ODk5OTUwMTg4",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCGb6lnsgvEGTw0CFrmo6ViQ",
        publishedAt: "2020-08-31T18:52:32.593000Z",
        hasDisplayContent: true,
        displayMessage: "6m op sir",
        textMessageDetails: {
          messageText: "6m op sir",
        },
      },
      authorDetails: {
        channelId: "UCGb6lnsgvEGTw0CFrmo6ViQ",
        channelUrl: "http://www.youtube.com/channel/UCGb6lnsgvEGTw0CFrmo6ViQ",
        displayName: "Vidit Kumar",
        profileImageUrl: "https://yt3.ggpht.com/-FOfuIKvR0jY/AAAAAAAAAAI/AAAAAAAAAAA/DjffE3WiS3U/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "cpqkXUHQU_QEXNZrN2pEWvEKb84",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSWpVMDc2T3h1c0NGVm02Z2dvZG1UWU5PZxInQ09laWdKcU94dXNDRlFIbU9BWWRMWVlMLVExNTk4ODk5OTUzMTg4",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCP_4x0PqH9ycFXbYiZOuGEA",
        publishedAt: "2020-08-31T18:52:34.706000Z",
        hasDisplayContent: true,
        displayMessage: "6Mop❤️♥️♥️❤️❤️♥️♥️❤️❤️😚😚😚😚😚😚😚",
        textMessageDetails: {
          messageText: "6Mop❤️♥️♥️❤️❤️♥️♥️❤️❤️😚😚😚😚😚😚😚",
        },
      },
      authorDetails: {
        channelId: "UCP_4x0PqH9ycFXbYiZOuGEA",
        channelUrl: "http://www.youtube.com/channel/UCP_4x0PqH9ycFXbYiZOuGEA",
        displayName: "Dipesh Maharjan",
        profileImageUrl: "https://yt3.ggpht.com/-8zMgxg-vq1A/AAAAAAAAAAI/AAAAAAAAAAA/1qUB-mXMDsg/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "vr1kBUx8Owx__Ffkd6rwY71sjzM",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSmZtMTc2T3h1c0NGU0hoZ2dvZEVQVUNqZxInQ0lxcmk3U094dXNDRlJmeWp3b2R3MndHT0ExNTk4ODk5OTU0NTI2",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC_I0zxZwluS6Zx3sEDasjDw",
        publishedAt: "2020-08-31T18:52:34.774000Z",
        hasDisplayContent: true,
        displayMessage: "6 m hogaya:yougotthis::yougotthis:❤️❤️",
        textMessageDetails: {
          messageText: "6 m hogaya:yougotthis::yougotthis:❤️❤️",
        },
      },
      authorDetails: {
        channelId: "UC_I0zxZwluS6Zx3sEDasjDw",
        channelUrl: "http://www.youtube.com/channel/UC_I0zxZwluS6Zx3sEDasjDw",
        displayName: "Chong Sangma",
        profileImageUrl: "https://yt3.ggpht.com/-FssYCx4__Lk/AAAAAAAAAAI/AAAAAAAAAAA/WcUyXEJ2rUo/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "aI-ZQKocFF26ayP86Xu1G_S1jxs",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSmYxXzctT3h1c0NGWkNHZ2dvZDNuZ0FaZxInQ1B6dzNhNk94dXNDRlpIM1VRb2Q2cE1JbVExNTk4ODk5OTU3MTA3",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC-kC9CRVeEvXRtXvFpCaV0A",
        publishedAt: "2020-08-31T18:52:37.529000Z",
        hasDisplayContent: true,
        displayMessage: "congrats:yt::yt::yt::yt:chats walo mujh bi subscribe kro",
        textMessageDetails: {
          messageText: "congrats:yt::yt::yt::yt:chats walo mujh bi subscribe kro",
        },
      },
      authorDetails: {
        channelId: "UC-kC9CRVeEvXRtXvFpCaV0A",
        channelUrl: "http://www.youtube.com/channel/UC-kC9CRVeEvXRtXvFpCaV0A",
        displayName: "IYI SAMAD",
        profileImageUrl: "https://yt3.ggpht.com/-eBdb_Ajx9jE/AAAAAAAAAAI/AAAAAAAAAAA/zGSjK4sYHG4/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "I8XFvLWCgOsBRxhVrg4OnlWm1Q8",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI6ChpDT3o2c3NDT3h1c0NGWkd3RFFvZFBMWUlJZxIcQ0pETXBMbU94dXNDRmNzcnR3QWRQZVVDUEEtMA",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCUBS4AdI5c7tEK5gHL3QqgQ",
        publishedAt: "2020-08-31T18:52:38.365000Z",
        hasDisplayContent: true,
        displayMessage: "6m",
        textMessageDetails: {
          messageText: "6m",
        },
      },
      authorDetails: {
        channelId: "UCUBS4AdI5c7tEK5gHL3QqgQ",
        channelUrl: "http://www.youtube.com/channel/UCUBS4AdI5c7tEK5gHL3QqgQ",
        displayName: "Kavi Khilnani",
        profileImageUrl: "https://yt3.ggpht.com/-2zWmvCL9IDs/AAAAAAAAAAI/AAAAAAAAAAA/Hlj9DP6F-r4/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "LMuBoy83KnOpkM-__iOf1ocgSR8",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTnE5cHNLT3h1c0NGUXBUN1FvZDZ3MEhhQRInQ01lMXlkNk54dXNDRlFMSWN3RWRjbWNJV3cxNTk4ODk5OTYxOTE4",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCo9IR70Ur0sp8-1PsEgOTIQ",
        publishedAt: "2020-08-31T18:52:42.355000Z",
        hasDisplayContent: true,
        displayMessage: "please shout out",
        textMessageDetails: {
          messageText: "please shout out",
        },
      },
      authorDetails: {
        channelId: "UCo9IR70Ur0sp8-1PsEgOTIQ",
        channelUrl: "http://www.youtube.com/channel/UCo9IR70Ur0sp8-1PsEgOTIQ",
        displayName: "how to Hack Game",
        profileImageUrl: "https://yt3.ggpht.com/-VYuKQ1LPZ5c/AAAAAAAAAAI/AAAAAAAAAAA/6NZuLulJIQE/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "JbQT6BxuvzcR_Dns9WHn-isV7B8",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSTc3dE1LT3h1c0NGWVRmZ2dvZDBRQUhYQRInQ002d19MdU94dXNDRmRqcU9BWWRkeG9LZkExNTk4ODk5OTYxNDYw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCOe5zdz0Xv7jUogBFbLY1ew",
        publishedAt: "2020-08-31T18:52:42.592000Z",
        hasDisplayContent: true,
        displayMessage: "6m❤️",
        textMessageDetails: {
          messageText: "6m❤️",
        },
      },
      authorDetails: {
        channelId: "UCOe5zdz0Xv7jUogBFbLY1ew",
        channelUrl: "http://www.youtube.com/channel/UCOe5zdz0Xv7jUogBFbLY1ew",
        displayName: "Akshay Yadav",
        profileImageUrl: "https://yt3.ggpht.com/-OH57fIyD2A8/AAAAAAAAAAI/AAAAAAAAAAA/JvNrGnnGYcc/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "tenzp02uFy4H6NwDlw34WkCJbts",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI5ChpDSmFDOHNLT3h1c0NGUkd3RFFvZDU2NEVfdxIbQ1BETjFmYUx4dXNDRlNUdE9BWWRnTGtKZFEx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCEVwIdB0sMKk_FNshOK_w4Q",
        publishedAt: "2020-08-31T18:52:43.592000Z",
        hasDisplayContent: true,
        displayMessage: "MUSLIM KI J",
        textMessageDetails: {
          messageText: "MUSLIM KI J",
        },
      },
      authorDetails: {
        channelId: "UCEVwIdB0sMKk_FNshOK_w4Q",
        channelUrl: "http://www.youtube.com/channel/UCEVwIdB0sMKk_FNshOK_w4Q",
        displayName: "Raksha Sheelavanatmath",
        profileImageUrl: "https://yt3.ggpht.com/-eWL7wk4oJh4/AAAAAAAAAAI/AAAAAAAAAAA/SbR2-L4hY-c/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "hww6KJp_C9E78cptDA5IDH85dYk",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTW5kMDhPT3h1c0NGUm1zRFFvZFc0WU15dxInQ1BfX3B2U054dXNDRlFMdGFBb2RSbXNJN0ExNTk4ODk5OTY0NjIy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCCLUen__BZnGt7OfjUEwfRg",
        publishedAt: "2020-08-31T18:52:45.193000Z",
        hasDisplayContent: true,
        displayMessage: "BOT BAI MORTAL",
        textMessageDetails: {
          messageText: "BOT BAI MORTAL",
        },
      },
      authorDetails: {
        channelId: "UCCLUen__BZnGt7OfjUEwfRg",
        channelUrl: "http://www.youtube.com/channel/UCCLUen__BZnGt7OfjUEwfRg",
        displayName: "Msr Srihari",
        profileImageUrl: "https://yt3.ggpht.com/-ZeYuasxFFQ0/AAAAAAAAAAI/AAAAAAAAAAA/PC9R_zAETKM/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "pCejvrIkIcHl04XAFHKb5N7YA70",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTS1vMGNPT3h1c0NGWG1Hd2dFZGNTa01idxInQ0kzUDY3Mk94dXNDRmI4VXR3QWQwcW9GZncxNTk4ODk5OTY0NjIx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCS4axORvJYP1ikgT3hnf6zQ",
        publishedAt: "2020-08-31T18:52:45.154000Z",
        hasDisplayContent: true,
        displayMessage: "6 min",
        textMessageDetails: {
          messageText: "6 min",
        },
      },
      authorDetails: {
        channelId: "UCS4axORvJYP1ikgT3hnf6zQ",
        channelUrl: "http://www.youtube.com/channel/UCS4axORvJYP1ikgT3hnf6zQ",
        displayName: "The Hero Gaming",
        profileImageUrl: "https://yt3.ggpht.com/-vJVjK6v4ldg/AAAAAAAAAAI/AAAAAAAAAAA/lodzOAy4SAk/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "cRxBRlDzrI5zb8uShPxyNb-oy90",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDT3loMmNTT3h1c0NGV05EN1FvZEJHSUUxZxInQ0p6WDNiLU94dXNDRldyZGN3RWROWXdFencxNTk4ODk5OTY2NDEz",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCMYnZxulogXJpxdPpylTL1Q",
        publishedAt: "2020-08-31T18:52:47.381000Z",
        hasDisplayContent: true,
        displayMessage: "6 million",
        textMessageDetails: {
          messageText: "6 million",
        },
      },
      authorDetails: {
        channelId: "UCMYnZxulogXJpxdPpylTL1Q",
        channelUrl: "http://www.youtube.com/channel/UCMYnZxulogXJpxdPpylTL1Q",
        displayName: "Rushi Sahu",
        profileImageUrl: "https://yt3.ggpht.com/-smrDKsWTEO4/AAAAAAAAAAI/AAAAAAAAAAA/5ijsy8DPt4A/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "7Yfv0xLqevmI3sBohFwwnc2ME2w",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDT0NCa3NXT3h1c0NGUU1CZ3dvZFZPb0o2QRInQ092THpMQ094dXNDRlhMSmN3RWRMcGtLeFExNTk4ODk5OTIyNjg0",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCf3F_vgVD4n8tRk3XmUSUfQ",
        publishedAt: "2020-08-31T18:52:48.311000Z",
        hasDisplayContent: true,
        displayMessage: ":thanksdoc::thanksdoc::thanksdoc:",
        textMessageDetails: {
          messageText: ":thanksdoc::thanksdoc::thanksdoc:",
        },
      },
      authorDetails: {
        channelId: "UCf3F_vgVD4n8tRk3XmUSUfQ",
        channelUrl: "http://www.youtube.com/channel/UCf3F_vgVD4n8tRk3XmUSUfQ",
        displayName: "Sankalp Katoch",
        profileImageUrl: "https://yt3.ggpht.com/-OFJxXHnR2lY/AAAAAAAAAAI/AAAAAAAAAAA/ztl6ScQlHcI/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "q9LbYeWyyfkhIMkSwGeYqHcqjv0",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSnVGdU1XT3h1c0NGUjZCd2dFZE1xNExfQRInQ0x1RXpKU094dXNDRlRreXR3QWR4dkFFdmcxNTk4ODk5OTY4NTg4",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC5yDU724-y_52-C0BNY6ipg",
        publishedAt: "2020-08-31T18:52:48.934000Z",
        hasDisplayContent: true,
        displayMessage: "owais ronak spam ignore",
        textMessageDetails: {
          messageText: "owais ronak spam ignore",
        },
      },
      authorDetails: {
        channelId: "UC5yDU724-y_52-C0BNY6ipg",
        channelUrl: "http://www.youtube.com/channel/UC5yDU724-y_52-C0BNY6ipg",
        displayName: "Gaurav Rahul",
        profileImageUrl: "https://yt3.ggpht.com/-t783t2MRARo/AAAAAAAAAAI/AAAAAAAAAAA/A1D_JMZ_Vvc/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "vr8rTi53mn3FMzIX-r_I3JCGHy0",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTFhOcjhXT3h1c0NGU2lFd2dFZDRWTUFIURInQ08tSGdzT094dXNDRlFlSGNBb2RrckFLM1ExNTk4ODk5OTY3OTMy",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCOMeFU26yS-sTUEpwZissIA",
        publishedAt: "2020-08-31T18:52:48.796000Z",
        hasDisplayContent: true,
        displayMessage: "6m bolte",
        textMessageDetails: {
          messageText: "6m bolte",
        },
      },
      authorDetails: {
        channelId: "UCOMeFU26yS-sTUEpwZissIA",
        channelUrl: "http://www.youtube.com/channel/UCOMeFU26yS-sTUEpwZissIA",
        displayName: "Ujjwal Goel",
        profileImageUrl: "https://yt3.ggpht.com/-JlH7XqvipTc/AAAAAAAAAAI/AAAAAAAAAAA/hs52xBfEc9k/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "v8DEeGf6xP8wdfpipTANr-8TAkw",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDUFhFanNhT3h1c0NGUW1JZ2dvZFk1TU8wdxInQ05uZHpiaU94dXNDRlhZVHR3QWQtMk1FencxNTk4ODk5ODcxMzU2",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCH-L579UrWkgd7IzSZ3vVAg",
        publishedAt: "2020-08-31T18:52:50.351000Z",
        hasDisplayContent: true,
        displayMessage: "6m op❤️🥀",
        textMessageDetails: {
          messageText: "6m op❤️🥀",
        },
      },
      authorDetails: {
        channelId: "UCH-L579UrWkgd7IzSZ3vVAg",
        channelUrl: "http://www.youtube.com/channel/UCH-L579UrWkgd7IzSZ3vVAg",
        displayName: "NIKHIL ñ",
        profileImageUrl: "https://yt3.ggpht.com/-Cd7zXa69U1I/AAAAAAAAAAI/AAAAAAAAAAA/HhxUd5VyrCk/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "5tVtz2JTnFK2hM8IKbCBjXCF0k0",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTHZvamNhT3h1c0NGWXZjZ2dvZElOb0dCZxInQ0pxY21MLU94dXNDRlgtRFl3WWRUTXdMdmcxNTk4ODk5OTY5MzIx",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCp7-rAMjJjTNlLnsrh74VoA",
        publishedAt: "2020-08-31T18:52:50.339000Z",
        hasDisplayContent: true,
        displayMessage: "6m",
        textMessageDetails: {
          messageText: "6m",
        },
      },
      authorDetails: {
        channelId: "UCp7-rAMjJjTNlLnsrh74VoA",
        channelUrl: "http://www.youtube.com/channel/UCp7-rAMjJjTNlLnsrh74VoA",
        displayName: "Durga Prasad",
        profileImageUrl: "https://yt3.ggpht.com/-YhEDyvyAG2w/AAAAAAAAAAI/AAAAAAAAAAA/T1s22XrRBYg/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "6zTpfXxr0SUf0NNbXuhxH1fGxi4",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDSmFNeDhhT3h1c0NGYlhrZ2dvZGNua0R4dxInQ0lfXzM4S094dXNDRlVFVzFRb2RXaTRBZVExNTk4ODk5OTcwNzI0",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCw00xkZwgy0yWpvwkn944Qg",
        publishedAt: "2020-08-31T18:52:51.278000Z",
        hasDisplayContent: true,
        displayMessage: "6 M",
        textMessageDetails: {
          messageText: "6 M",
        },
      },
      authorDetails: {
        channelId: "UCw00xkZwgy0yWpvwkn944Qg",
        channelUrl: "http://www.youtube.com/channel/UCw00xkZwgy0yWpvwkn944Qg",
        displayName: "Preetham Kumar",
        profileImageUrl: "https://yt3.ggpht.com/-XumKPDHiBtg/AAAAAAAAAAI/AAAAAAAAAAA/pze1shPeqB8/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "832Y7Rto4oP05FzeFCDuVc2J2Bk",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDS3E4LU1hT3h1c0NGVmVnZ2dvZERKNFBhZxInQ01LbzJQYU14dXNDRlhURGN3RWQtc2NMQUExNTk4ODk5OTcxNDUw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UC5rzjzHlGE9Ja26Hj9MKvjA",
        publishedAt: "2020-08-31T18:52:52.087000Z",
        hasDisplayContent: true,
        displayMessage: "hi",
        textMessageDetails: {
          messageText: "hi",
        },
      },
      authorDetails: {
        channelId: "UC5rzjzHlGE9Ja26Hj9MKvjA",
        channelUrl: "http://www.youtube.com/channel/UC5rzjzHlGE9Ja26Hj9MKvjA",
        displayName: "Razia Sultana",
        profileImageUrl: "https://yt3.ggpht.com/-137hAY_PQdM/AAAAAAAAAAI/AAAAAAAAAAA/T7cSWymE4yI/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "pDLqktYBGtnmlPaj5VYV5F3aYiY",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDT185OThhT3h1c0NGWnlDd2dFZFd0SU5adxInQ0stdHlyLU94dXNDRlJQbE9BWWRRRHNBUmcxNTk4OTAwMDI2Mzk0",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCoW_6ThUs8VCsr5Zu7KmN1A",
        publishedAt: "2020-08-31T18:52:52.079000Z",
        hasDisplayContent: true,
        displayMessage: "6m gg❤️❤️🙏",
        textMessageDetails: {
          messageText: "6m gg❤️❤️🙏",
        },
      },
      authorDetails: {
        channelId: "UCoW_6ThUs8VCsr5Zu7KmN1A",
        channelUrl: "http://www.youtube.com/channel/UCoW_6ThUs8VCsr5Zu7KmN1A",
        displayName: "Justin jayan paul",
        profileImageUrl: "https://yt3.ggpht.com/-MEUjb7w7LGA/AAAAAAAAAAI/AAAAAAAAAAA/Y90kiqC8_84/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "V2j4C3z05K5Ufa0qOVymVa4swL4",
      id: "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRIcChpDT2ZRd01lT3h1c0NGVVN5Z2dvZE1uY0JCdw",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        publishedAt: "2020-08-31T18:52:53.269000Z",
        hasDisplayContent: true,
        displayMessage: "Hello @Razia Sultana welcome to the stream 😍",
        textMessageDetails: {
          messageText: "Hello @Razia Sultana welcome to the stream 😍",
        },
      },
      authorDetails: {
        channelId: "UCSvjQBDgYDB5TGVmCZObcwA",
        channelUrl: "http://www.youtube.com/channel/UCSvjQBDgYDB5TGVmCZObcwA",
        displayName: "Nightbot",
        profileImageUrl: "https://yt3.ggpht.com/-TGo4_AHc7Po/AAAAAAAAAAI/AAAAAAAAAAA/6X489lMTauA/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: true,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: true,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "GNf922ytn4IXjmv0667SUE_lgmQ",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRI6ChpDSVgzejhlT3h1c0NGUnBUN1FvZFFCWUFLZxIcQ0lxVjBjV094dXNDRlJWMWp3b2R4S2NIeUEtMA",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCqDU82j3AVAnERf5l9DMyVA",
        publishedAt: "2020-08-31T18:52:53.520000Z",
        hasDisplayContent: true,
        displayMessage: "Raghav_singhania99 add me on insta only girls",
        textMessageDetails: {
          messageText: "Raghav_singhania99 add me on insta only girls",
        },
      },
      authorDetails: {
        channelId: "UCqDU82j3AVAnERf5l9DMyVA",
        channelUrl: "http://www.youtube.com/channel/UCqDU82j3AVAnERf5l9DMyVA",
        displayName: "Raghav Singhania",
        profileImageUrl: "https://yt3.ggpht.com/-Sc5Qr4P1Ng0/AAAAAAAAAAI/AAAAAAAAAAA/Nro3Bu_9Gpg/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
    {
      kind: "youtube#liveChatMessage",
      etag: "ECaGV7jGN_d6_POR1mUzPEGEt8E",
      id:
        "LCC.CjgKDQoLWE1xZU50Rjlzak0qJwoYVUM3UTdwbDB6ME1yZGF5dm1BbmNobEpREgtYTXFlTnRGOXNqTRJFChpDTVhyZ3NpT3h1c0NGUUdaZ2dvZElpc0MwURInQ09yeTdfV054dXNDRlRuM09BWWRLZXNOR1ExNTk4ODk5OTczNzI2",
      snippet: {
        type: "textMessageEvent",
        liveChatId: "Cg0KC1hNcWVOdEY5c2pNKicKGFVDN1E3cGwwejBNcmRheXZtQW5jaGxKURILWE1xZU50Rjlzak0",
        authorChannelId: "UCoKBbAxl-1gYuiZ2WX_RFKQ",
        publishedAt: "2020-08-31T18:52:54.354000Z",
        hasDisplayContent: true,
        displayMessage: "6M Op boltr",
        textMessageDetails: {
          messageText: "6M Op boltr",
        },
      },
      authorDetails: {
        channelId: "UCoKBbAxl-1gYuiZ2WX_RFKQ",
        channelUrl: "http://www.youtube.com/channel/UCoKBbAxl-1gYuiZ2WX_RFKQ",
        displayName: "Atif khan",
        profileImageUrl: "https://yt3.ggpht.com/-UH96cg8WKYI/AAAAAAAAAAI/AAAAAAAAAAA/8RjwuogDBHw/s88-c-k-no-mo-rj-c0xffffff/photo.jpg",
        isVerified: false,
        isChatOwner: false,
        isChatSponsor: false,
        isChatModerator: false,
      },
    },
  ],
};
